name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd code
      run: export PWD=/home/runner/work/cc/cc/code
    - name: directory_check
      run: pwd
    - name: make
      run: make
    - name: make test
      run: make test
