name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd code
      run: cd code
    - name: directory_check
    - run: pwd
    - name: make
      run: if make
    - name: make test
      run: make test
